### ISSUE TITLE
practica de tablas de verdad 

### ISSUE THREAD

**Issue by AlynGomez12** [SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-equipo-f4#1]
[Practica 2 crocodile.pdf](https://github.com/user-attachments/files/17484185/Practica.2.crocodile.pdf)

**Comment by mae18-25** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:24/25
Total:99/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
